### ISSUE TITLE
HTTPS/SSL Support

### ISSUE THREAD

**Issue by 3goats** [matadon/mizuno#31]
Can Mizuno support SSL - if so do you have some examples. 

Regards,

Carl

**Comment by YuriSolovyov** [comment]
Can I activate https with command-line params?
ATM my cmd looks like so:
```
java 
  -jar lib/jruby-complete-1.7.21.jar 
  -X+O 
  -S rackup --server mizuno 
  -I lib --env development --host 127.0.0.1 --port 8081 config.ru
```

**Comment by matadon** [comment]
On Sep 17, 2015, at 00:03 , Yuri <notifications@github.com> wrote:
> 
> Can I activate https with command-line params?

Unfortunately, not at this time, as getting SSL set up in Java is a bit of a nightmare, at least as of the last time I dived into it.
